import exceptions
print dir(exceptions)
